[package]
name = "apexclone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
dotenv = "0.15.0"
poise = "0.5.5"
tokio = { version = "1.28.1", features = ["rt-multi-thread"] }
